# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
configs = YAML.load_file("#{current_dir}/config.yaml")
vagrant_config = configs['configs'][configs['configs']['use']]

# Install vagrant-disksize to allow resizing the vagrant box disk.
unless Vagrant.has_plugin?("vagrant-disksize")
  raise  Vagrant::Errors::VagrantError.new, "vagrant-disksize plugin is missing. Please install it using 'vagrant plugin install vagrant-disksize' and rerun 'vagrant up'"
end

Vagrant.configure("2") do |config|

  config.vm.box = "archlinux/archlinux"
  config.disksize.size = vagrant_config['disksize']
  config.vm.box_check_update = false
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = vagrant_config['name']
    vb.gui = true
    vb.cpus = vagrant_config['cpus']
    vb.memory = vagrant_config['memory']
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    chmod +x /vagrant/setup.sh
    sudo /vagrant/setup.sh
  SHELL

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "ansible/playbook.yml"
  end
end
