#!/usr/bin/env sh

# Define sxiv keyboard shortcuts.
# Handler is called by sxiv after the external prefix key (Ctrl-x by default) is pressed.
# Example: Press 'Ctrl-x' then 'y' to copy the image to the clipboard


while read file ; do
    case "$1" in
        "r")
            [ ! -z "$(command -v convert)" ] && convert -rotate 90 "$file" "$file" ;;
        "R")
            [ ! -z "$(command -v convert)" ] && convert -rotate -90 "$file" "$file" ;;
        "f")
            [ ! -z "$(command -v convert)" ] && convert -flop "$file" "$file" ;;
        "y")
            echo -n "$file" | xclip -selection clipboard &&
            notify-send "$file copied to clipboard" ;;
        "Y")
            [ ! -z "$(command -v readlink)" ] && readlink -f "$file" | xclip -selection clipboard &&
            notify-send "$(readlink -f "$file") copied to clipboard" ;;
        "d")
            [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted" ;;
        "g")
            [ ! -z "$(command -v gimp)" ] && gimp "$file" & ;;
    esac
done
