---
configs:
  use: 'minimal1'
  minimal1:
    name: 'Vagrant-Arch-Minimal'
    cpus: 4
    memory: 4096
    disksize: '40GB'
  minimal2:
    name: 'Vagrant-Arch-Minimal'
    cpus: 4
    memory: 4096
    disksize: '30GB'
